# Generated by Django 5.0.6 on 2024-06-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students',
            new_name='guruh',
        ),
    ]
