# Generated by Django 5.0.2 on 2024-07-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_daycomplated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='usrename',
            new_name='username',
        ),
    ]
